name: Monitor Server Status

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering as well

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code (optional if needed for other steps)
    - name: Checkout code
      uses: actions/checkout@v3

    # Make the GET request and check the response
    - name: Make GET request and check response
      id: http_request
      run: |
        RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null http://tracker.way.today:8001/1/pingx)
        BODY=$(curl --silent http://tracker.way.today:8001/1/ping)
        echo "Response Code: $RESPONSE"
        echo "Response Body: $BODY"
        if [ "$RESPONSE" -ne 200 ] || [ "$BODY" != "Pong" ]; then
          echo "Error: Server returned non-200 response code or incorrect body"
          echo "::set-output name=status::failed"
        else
          echo "::set-output name=status::success"
        fi

    # Report to Slack if response is non-200 or incorrect body
    - name: Send Slack Notification if failed
      if: steps.http_request.outputs.status == 'failed'
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}'  ${{ secrets.SLACK_URL }}
